language : python
python:
  - "3.6"
install:
  - pip install -r requirement.txt
  - pip install coveralls
# looks through the specific files to test their functionality

script: pytest -v --cov --cov-report term-missing
after success:
    - coveralls

